<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EMPLOYEE_INFORMATION</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeSystem.BL\EmployeeSystem.BL.csproj" />
    <ProjectReference Include="..\EmployeeSystem.DL\EmployeeSystem.DL.csproj" />
    <ProjectReference Include="..\EmployeeSystem.Models\EmployeeSystem.Models.csproj" />
  </ItemGroup>

</Project>
